import type { DeckConfig } from '@/decks/types';

// Word list transcribed verbatim from the dolch-k-5 table in
// specs/001-deck-runs/research.md §4. The rung boundaries no longer match that
// table: the 50-word rung was deleted so the deck does not end on a two-card
// part-step, and all 52 cards belong to the top rung alone (008 FR-020).
// Rungs are cumulative: each lists every card literally, in presentation order.

export const dolchK5: DeckConfig = {
  id: 'dolch-k-5',
  title: 'Dolch Kindergarten · Steps of 5',
  cards: [
    { id: 'am', front: 'am' },
    { id: 'at', front: 'at' },
    { id: 'on', front: 'on' },
    { id: 'so', front: 'so' },
    { id: 'no', front: 'no' },
    { id: 'be', front: 'be' },
    { id: 'do', front: 'do' },
    { id: 'he', front: 'he' },
    { id: 'all', front: 'all' },
    { id: 'get', front: 'get' },
    { id: 'did', front: 'did' },
    { id: 'but', front: 'but' },
    { id: 'yes', front: 'yes' },
    { id: 'ran', front: 'ran' },
    { id: 'out', front: 'out' },
    { id: 'are', front: 'are' },
    { id: 'ate', front: 'ate' },
    { id: 'eat', front: 'eat' },
    { id: 'new', front: 'new' },
    { id: 'now', front: 'now' },
    { id: 'our', front: 'our' },
    { id: 'saw', front: 'saw' },
    { id: 'say', front: 'say' },
    { id: 'she', front: 'she' },
    { id: 'too', front: 'too' },
    { id: 'was', front: 'was' },
    { id: 'who', front: 'who' },
    { id: 'will', front: 'will' },
    { id: 'with', front: 'with' },
    { id: 'that', front: 'that' },
    { id: 'this', front: 'this' },
    { id: 'they', front: 'they' },
    { id: 'want', front: 'want' },
    { id: 'well', front: 'well' },
    { id: 'went', front: 'went' },
    { id: 'came', front: 'came' },
    { id: 'good', front: 'good' },
    { id: 'have', front: 'have' },
    { id: 'into', front: 'into' },
    { id: 'like', front: 'like' },
    { id: 'must', front: 'must' },
    { id: 'ride', front: 'ride' },
    { id: 'soon', front: 'soon' },
    { id: 'four', front: 'four' },
    { id: 'what', front: 'what' },
    { id: 'black', front: 'black' },
    { id: 'brown', front: 'brown' },
    { id: 'there', front: 'there' },
    { id: 'under', front: 'under' },
    { id: 'white', front: 'white' },
    { id: 'please', front: 'please' },
    { id: 'pretty', front: 'pretty' },
  ],
  rungs: [
    {
      id: 'r1',
      label: 'Level 1',
      cardIds: ['am', 'at', 'on', 'so', 'no'],
    },
    {
      id: 'r2',
      label: 'Level 2',
      cardIds: ['am', 'at', 'on', 'so', 'no', 'be', 'do', 'he', 'all', 'get'],
    },
    {
      id: 'r3',
      label: 'Level 3',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
      ],
    },
    {
      id: 'r4',
      label: 'Level 4',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
      ],
    },
    {
      id: 'r5',
      label: 'Level 5',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
      ],
    },
    {
      id: 'r6',
      label: 'Level 6',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
        'was',
        'who',
        'will',
        'with',
        'that',
      ],
    },
    {
      id: 'r7',
      label: 'Level 7',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
        'was',
        'who',
        'will',
        'with',
        'that',
        'this',
        'they',
        'want',
        'well',
        'went',
      ],
    },
    {
      id: 'r8',
      label: 'Level 8',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
        'was',
        'who',
        'will',
        'with',
        'that',
        'this',
        'they',
        'want',
        'well',
        'went',
        'came',
        'good',
        'have',
        'into',
        'like',
      ],
    },
    {
      id: 'r9',
      label: 'Level 9',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
        'was',
        'who',
        'will',
        'with',
        'that',
        'this',
        'they',
        'want',
        'well',
        'went',
        'came',
        'good',
        'have',
        'into',
        'like',
        'must',
        'ride',
        'soon',
        'four',
        'what',
      ],
    },
    {
      id: 'r11',
      label: 'Full deck',
      cardIds: [
        'am',
        'at',
        'on',
        'so',
        'no',
        'be',
        'do',
        'he',
        'all',
        'get',
        'did',
        'but',
        'yes',
        'ran',
        'out',
        'are',
        'ate',
        'eat',
        'new',
        'now',
        'our',
        'saw',
        'say',
        'she',
        'too',
        'was',
        'who',
        'will',
        'with',
        'that',
        'this',
        'they',
        'want',
        'well',
        'went',
        'came',
        'good',
        'have',
        'into',
        'like',
        'must',
        'ride',
        'soon',
        'four',
        'what',
        'black',
        'brown',
        'there',
        'under',
        'white',
        'please',
        'pretty',
      ],
    },
  ],
};
