import type { DeckConfig } from '@/decks/types';

// Word list and rung boundaries transcribed verbatim from the dolch-prek-5 table in
// specs/001-deck-runs/research.md §4.
// Rungs are cumulative: each lists every card literally, in presentation order.

export const dolchPreK5: DeckConfig = {
  id: 'dolch-prek-5',
  title: 'Dolch Pre-K · Steps of 5',
  cards: [
    { id: 'a', front: 'a' },
    { id: 'i', front: 'I' },
    { id: 'the', front: 'the' },
    { id: 'and', front: 'and' },
    { id: 'to', front: 'to' },
    { id: 'is', front: 'is' },
    { id: 'it', front: 'it' },
    { id: 'in', front: 'in' },
    { id: 'up', front: 'up' },
    { id: 'me', front: 'me' },
    { id: 'go', front: 'go' },
    { id: 'we', front: 'we' },
    { id: 'my', front: 'my' },
    { id: 'see', front: 'see' },
    { id: 'can', front: 'can' },
    { id: 'not', front: 'not' },
    { id: 'run', front: 'run' },
    { id: 'big', front: 'big' },
    { id: 'red', front: 'red' },
    { id: 'you', front: 'you' },
    { id: 'for', front: 'for' },
    { id: 'help', front: 'help' },
    { id: 'look', front: 'look' },
    { id: 'come', front: 'come' },
    { id: 'down', front: 'down' },
    { id: 'play', front: 'play' },
    { id: 'make', front: 'make' },
    { id: 'here', front: 'here' },
    { id: 'blue', front: 'blue' },
    { id: 'said', front: 'said' },
    { id: 'away', front: 'away' },
    { id: 'find', front: 'find' },
    { id: 'jump', front: 'jump' },
    { id: 'little', front: 'little' },
    { id: 'three', front: 'three' },
    { id: 'funny', front: 'funny' },
    { id: 'one', front: 'one' },
    { id: 'two', front: 'two' },
    { id: 'where', front: 'where' },
    { id: 'yellow', front: 'yellow' },
  ],
  rungs: [
    {
      id: 'r1',
      label: 'Level 1',
      cardIds: ['a', 'i', 'the', 'and', 'to'],
    },
    {
      id: 'r2',
      label: 'Level 2',
      cardIds: ['a', 'i', 'the', 'and', 'to', 'is', 'it', 'in', 'up', 'me'],
    },
    {
      id: 'r3',
      label: 'Level 3',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
      ],
    },
    {
      id: 'r4',
      label: 'Level 4',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
        'not',
        'run',
        'big',
        'red',
        'you',
      ],
    },
    {
      id: 'r5',
      label: 'Level 5',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
        'not',
        'run',
        'big',
        'red',
        'you',
        'for',
        'help',
        'look',
        'come',
        'down',
      ],
    },
    {
      id: 'r6',
      label: 'Level 6',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
        'not',
        'run',
        'big',
        'red',
        'you',
        'for',
        'help',
        'look',
        'come',
        'down',
        'play',
        'make',
        'here',
        'blue',
        'said',
      ],
    },
    {
      id: 'r7',
      label: 'Level 7',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
        'not',
        'run',
        'big',
        'red',
        'you',
        'for',
        'help',
        'look',
        'come',
        'down',
        'play',
        'make',
        'here',
        'blue',
        'said',
        'away',
        'find',
        'jump',
        'little',
        'three',
      ],
    },
    {
      id: 'r8',
      label: 'Full deck',
      cardIds: [
        'a',
        'i',
        'the',
        'and',
        'to',
        'is',
        'it',
        'in',
        'up',
        'me',
        'go',
        'we',
        'my',
        'see',
        'can',
        'not',
        'run',
        'big',
        'red',
        'you',
        'for',
        'help',
        'look',
        'come',
        'down',
        'play',
        'make',
        'here',
        'blue',
        'said',
        'away',
        'find',
        'jump',
        'little',
        'three',
        'funny',
        'one',
        'two',
        'where',
        'yellow',
      ],
    },
  ],
};
